version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql_database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dockerexample
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

  spring-app:
    build: .
    container_name: spring_application
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dockerexample
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password

volumes:
  mysql_data: