version: '3'

services:

  spring-app:
    build: .
    container_name: spring_application
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    env_file:
      - .env.docker

  mysql:
    image: mysql:8.3.0
    container_name: mysql_database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dockerexample
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: